Bugfix - Trigger configuration does not list repositories
jfrog/teamcity-artifactory-plugin pull request #105
Opened 2022-04-26 15:05 UTC by talarian1

Fixes [TCAP-1165](https://www.jfrog.com/jira/browse/TCAP-1165).

2022-05-01 08:24 UTC, yahavi requested changes

2022-05-01 08:24 UTC, yahavi commented on ci/pipelines.release.yml
> +
```suggestion
```

2022-05-01 08:24 UTC, yahavi commented on ci/pipelines.release.yml
> +            - jf audit --fail=false
Let's move audit to below git tag

2022-05-01 08:24 UTC, yahavi commented on ci/pipelines.release.yml
>                env -i PATH=$PATH M2_HOME=$M2_HOME HOME=$HOME
```suggestion
              env -i PATH=$PATH HOME=$HOME
```

2022-05-01 08:24 UTC, yahavi commented on ci/pipelines.release.yml
>              # Show tests in the *Tests* tab
res_teamcityGit_resourcePath -> res_teamcityReleaseGit_resourcePath

2022-05-01 08:24 UTC, yahavi commented on ci/pipelines.release.yml
> +              --repo-deploy-releases ecosys-oss-release-local --repo-deploy-snapshots  ecosys-oss-snapshot-local
```suggestion
              --repo-deploy-releases ecosys-oss-release-local --repo-deploy-snapshots ecosys-oss-snapshot-local
```

2022-05-01 08:24 UTC, yahavi commented on ci/pipelines.snapshot.yml
> +            - jf  mvnc
```suggestion
            - jf mvnc
```

2022-05-01 08:24 UTC, yahavi commented on ci/pipelines.snapshot.yml
> +              --repo-deploy-releases ecosys-oss-release-local --repo-deploy-snapshots  ecosys-oss-snapshot-local
```suggestion
              --repo-deploy-releases ecosys-oss-release-local --repo-deploy-snapshots ecosys-oss-snapshot-local
```

2022-05-01 08:24 UTC, yahavi commented on ci/pipelines.snapshot.yml
> +              env -i PATH=$PATH
```suggestion
              env -i PATH=$PATH HOME=$HOME
```

2022-05-01 08:24 UTC, yahavi commented on server/src/main/java/org/jfrog/teamcity/server/global/DeployableArtifactoryServers.java
> +                    List<String> localRepos = client.getLocalRepositoriesKeys();
Let's close the clients in all file using the try-with-resources algorithm

2022-05-01 08:29 UTC, yahavi commented on agent/src/main/java/org/jfrog/teamcity/agent/MavenBuildInfoExtractor.java
> +                        dependencyBuilder.addRequestedBy(new String[]{idText});
```suggestion
                        dependencyBuilder.addRequestedBy(new String[]{idText, moduleId});
```

2022-05-01 12:38 UTC, yahavi approved these changes
LGTM

2022-06-02 06:52 UTC, kasperpagh commented
Thank you for fixing this :-) 

Best regards 
- Someone who wants to use this plugin ;-)

2022-06-05 10:38 UTC, eyalbe4 approved these changes

2022-06-08 14:49 UTC, merged